### PR TITLE
Modify consul_validate_checks to work with ruby 1.8

### LINKED ISSUE #148: Ruby 1.8 support
Ruby 1.8 isn't supported at the moment, as within https://github.com/solarkennedy/puppet-consul/blob/master/lib/puppet/parser/functions/consul_validate_checks.rb, it is trying to call 'Puppet::ParseError' as a function. Which results in 

```
undefined method `ParseError' for Puppet:Module at /etc/puppet/ext_modules/consul/manifests/service.pp:36 on node ip-172-18-0-234.ec2.internal
```

It appears that I can fix this by using `raise(Puppet::ParseError, 'message')` rather than `raise Puppet::ParseError('message')`, however I'm not a ruby developer so I'm not sure if this is the correct change to make or not.

Ruby 1.8 is the default ruby on Ubuntu 12.04 (which is why this is causing me issues). Would you be interested in a patch to fix support for 1.8 on this system configuration?

### PR DESCRIPTION
**Pull request by solarnz**
Fixes #148 

This adds ruby 1.8 support, which only involved changing the requirements in Gemfile and changing how exceptions are raised in consul_validate_checks.rb.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Great!

**Comment by solarkennedy** [comment]
Sorry, I had to undo the travis part of this, as we were not properly installing the correct puppet version before.

The rest of your changes are still in place though.
